disabled_rules: # rule identifiers turned on by default to exclude from running
- trailing_whitespace
- force_cast

line_length: 180

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- SurveysTests
- Surveys/SceneDelegate.swift
